/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Persistencia.alumnoData;
import Persistencia.inscripcionData;
import Persistencia.materiaData;
import javax.swing.JInternalFrame;

/**
 *
 * @author LaMaquina
 */
public class MenuPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipal.class.getName());

    private final alumnoData alumnoData;
    private final materiaData materiaData;
    private final inscripcionData inscripcionData;

    public MenuPrincipal(alumnoData alumnoData, materiaData materiaData, inscripcionData inscripcionData) {
        initComponents();
        this.alumnoData = alumnoData;
        this.materiaData = materiaData;
        this.inscripcionData = inscripcionData;
    }

    public void abrirInternal(JInternalFrame nuevo) {
        for (JInternalFrame frame : Escritorio.getAllFrames()) {
            frame.dispose();
        }
        Escritorio.add(nuevo);
        nuevo.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        Alumnos = new javax.swing.JMenu();
        Materias = new javax.swing.JMenu();
        Inscripciones = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Escritorio.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 747, Short.MAX_VALUE)
        );

        Alumnos.setText("Alumnos");
        Alumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AlumnosMouseClicked(evt);
            }
        });
        jMenuBar1.add(Alumnos);

        Materias.setText("Materias");
        Materias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MateriasMouseClicked(evt);
            }
        });
        jMenuBar1.add(Materias);

        Inscripciones.setText("Inscripciones");
        Inscripciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InscripcionesMouseClicked(evt);
            }
        });
        jMenuBar1.add(Inscripciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlumnosMouseClicked
        VistaAlumno va  = new VistaAlumno(alumnoData);
        abrirInternal(va);
    }//GEN-LAST:event_AlumnosMouseClicked

    private void MateriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MateriasMouseClicked
        VistaMateria vm = new VistaMateria(materiaData);
        abrirInternal(vm);
    }//GEN-LAST:event_MateriasMouseClicked

    private void InscripcionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InscripcionesMouseClicked
        VistaInscripcion vi = new VistaInscripcion(alumnoData, materiaData, inscripcionData);
        abrirInternal(vi);
    }//GEN-LAST:event_InscripcionesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Alumnos;
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenu Inscripciones;
    private javax.swing.JMenu Materias;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
