/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Modelo.Materia;
import Persistencia.materiaData;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LaMaquina
 */
public class VistaMateria extends javax.swing.JInternalFrame {

    Materia materia ;
    materiaData materiaData;
    public VistaMateria(materiaData materiaData) {
        initComponents();
        this.materiaData=materiaData;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        butBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaMaterias = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtIdMateria = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMateriaNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAño = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        butGuardar = new javax.swing.JButton();
        butNuevo = new javax.swing.JButton();
        butDarAltayBaja = new javax.swing.JButton();
        butActualizar = new javax.swing.JButton();
        butEliminar = new javax.swing.JButton();
        butLimpiar = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        jLabel1.setText("Buscar Materia");

        butBuscar.setText("Buscar");
        butBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butBuscarActionPerformed(evt);
            }
        });

        TablaMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "ID", "Materia", "Año", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TablaMaterias.setEnabled(false);
        TablaMaterias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMateriasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaMaterias);

        jLabel2.setText("Id_Materia");

        jLabel3.setText("Materia");

        jLabel4.setText("Año");

        txtAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAñoActionPerformed(evt);
            }
        });

        jLabel5.setText("Estado");

        butGuardar.setText("Guardar");
        butGuardar.setEnabled(false);
        butGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butGuardarActionPerformed(evt);
            }
        });

        butNuevo.setText("Nuevo");
        butNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butNuevoActionPerformed(evt);
            }
        });

        butDarAltayBaja.setText("Dar de Alta/Baja");
        butDarAltayBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDarAltayBajaActionPerformed(evt);
            }
        });

        butActualizar.setText("Actualizar");
        butActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butActualizarActionPerformed(evt);
            }
        });

        butEliminar.setText("Eliminar");
        butEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butEliminarActionPerformed(evt);
            }
        });

        butLimpiar.setText("Limpiar");
        butLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(butBuscar)
                .addGap(85, 85, 85))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtMateriaNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                        .addComponent(txtAño)
                                        .addComponent(txtEstado))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(butNuevo)
                                .addGap(28, 28, 28)
                                .addComponent(butDarAltayBaja)
                                .addGap(37, 37, 37)
                                .addComponent(butActualizar)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(butEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(butLimpiar)
                                    .addComponent(butGuardar))))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMateriaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(butGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(butLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(butActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(butEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(butDarAltayBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(butNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butBuscarActionPerformed
       String buscarMateria = txtBuscar.getText();
        int idMateria = 0;

        if (buscarMateria.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un Id", "Atencion", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            idMateria = Integer.parseInt(buscarMateria);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Tipo de dato no valido", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        materia = materiaData.buscarMateria(idMateria);

        if (materia == null) {
            JOptionPane.showMessageDialog(this, "No se encontro la materia con el Id", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        DefaultTableModel modelo = (DefaultTableModel) TablaMaterias.getModel();
        modelo.setRowCount(0);
        Object[] fila = {materia.getIdMateria(), materia.getNombre(), materia.getAño(), materia.isEstado()};
        modelo.addRow(fila);
    }//GEN-LAST:event_butBuscarActionPerformed

    private void txtAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAñoActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void butActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butActualizarActionPerformed
         String sIdMateria = txtIdMateria.getText();
        int dni = Integer.parseInt(sIdMateria);
        String sNombre = txtMateriaNombre.getText();
        String sAño = txtAño.getText();  
        String sEstado = txtEstado.getText();
        boolean estado = Boolean.parseBoolean(sEstado);
        materiaData.actualizarMateria(materia.getIdMateria(), "nombre", sNombre);
        materiaData.actualizarMateria(materia.getIdMateria(), "año", sAño);
        materiaData.actualizarMateria(materia.getIdMateria(), "estado", sEstado);
        butGuardar.setEnabled(true);
    }//GEN-LAST:event_butActualizarActionPerformed

    private void butEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butEliminarActionPerformed
        materiaData.eliminarMateria(materia.getIdMateria());
        butGuardar.setEnabled(true);
    }//GEN-LAST:event_butEliminarActionPerformed

    private void butDarAltayBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDarAltayBajaActionPerformed
        
        if (materia.isEstado() == false) {
            materiaData.DarAltaMateria(materia.getIdMateria());
            butGuardar.setEnabled(true);

        } else {
            materiaData.DarBajaMateria(materia.getIdMateria());
            butGuardar.setEnabled(true);
        }

    }//GEN-LAST:event_butDarAltayBajaActionPerformed

    private void butLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLimpiarActionPerformed
        txtIdMateria.setText("");
        txtMateriaNombre.setText("");
        txtAño.setText("");
        txtEstado.setText("");
        txtEstado.setEditable(true);
    }//GEN-LAST:event_butLimpiarActionPerformed

    private void butGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butGuardarActionPerformed
         JOptionPane.showMessageDialog(null, "SE GUARDO EXITOSAMENTE!", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        DefaultTableModel modelo = (DefaultTableModel) TablaMaterias.getModel();
        modelo.setRowCount(0);
        txtBuscar.setText("");
        txtIdMateria.setText("");
        txtMateriaNombre.setText("");
        txtAño.setText("");
        txtEstado.setText("");
        butGuardar.setEnabled(false);
        txtEstado.setEditable(true);
    }//GEN-LAST:event_butGuardarActionPerformed

    private void TablaMateriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMateriasMouseClicked
        txtIdMateria.setText(String.valueOf(materia.getIdMateria()));
        txtMateriaNombre.setText(materia.getNombre());
        txtAño.setText(String.valueOf(materia.getAño()));
        txtEstado.setText(String.valueOf(materia.isEstado()));
        txtEstado.setEditable(false);
        txtIdMateria.setEnabled(false);
    }//GEN-LAST:event_TablaMateriasMouseClicked

    private void butNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butNuevoActionPerformed
       
       
        String sNombre = txtMateriaNombre.getText();
        String sAño = txtAño.getText();
        String sEstado = txtEstado.getText();

        if (sNombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un DNI", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (sAño.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un Apellido", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (sEstado.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un Nombre", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

      

        int año;
        boolean estado;
        try {
            año = Integer.parseInt(sAño);
            estado = Boolean.parseBoolean(sEstado);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Tipo de dato no valido", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //Conversion
        materia = new Materia(-1, sNombre, año, estado);
        materiaData.guardarMateria(materia);
        butGuardar.setEnabled(true);
    }//GEN-LAST:event_butNuevoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaMaterias;
    private javax.swing.JButton butActualizar;
    private javax.swing.JButton butBuscar;
    private javax.swing.JButton butDarAltayBaja;
    private javax.swing.JButton butEliminar;
    private javax.swing.JButton butGuardar;
    private javax.swing.JButton butLimpiar;
    private javax.swing.JButton butNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtIdMateria;
    private javax.swing.JTextField txtMateriaNombre;
    // End of variables declaration//GEN-END:variables
}
