/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Modelo.Alumno;
import Modelo.Inscripcion;
import Modelo.Materia;
import Persistencia.alumnoData;
import Persistencia.inscripcionData;
import Persistencia.materiaData;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class VistaInscripcion extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaInscripcion
     */
    private alumnoData alumnoData;
    private final inscripcionData inscripcionData;
    private final ArrayList<Materia> materias;
    
    public VistaInscripcion(alumnoData alumnoData, materiaData materiaData, inscripcionData inscripcionData) {
        initComponents();
        this.alumnoData = alumnoData;
        this.inscripcionData = inscripcionData;
        this.materias = materiaData.listarMaterias();
        
        cargarAlumnos();
    }
    
    private void cargarAlumnos() {
        alumnoComboBox.removeAllItems();
        
        ArrayList<String> apellidoAlumnos = new ArrayList<>();
        ArrayList<Alumno> alumnos = alumnoData.listarAlumnos();
        
        for (Alumno a : alumnos) {
            apellidoAlumnos.add(a.getApellido() + " - " + a.getIdAlumno());
        }
        
        for (String apellido : apellidoAlumnos) {
            alumnoComboBox.addItem(apellido);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        alumnoComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        buttInscripta = new javax.swing.JRadioButton();
        buttNOInscripta = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        inscripcionTable = new javax.swing.JTable();
        butInscribir = new javax.swing.JButton();
        butAnularInscripcion = new javax.swing.JButton();
        butSalir = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("FORMULARIO DE INSCRIPCÍON");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Alumno");

        alumnoComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alumnoComboBoxMouseClicked(evt);
            }
        });
        alumnoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alumnoComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("LISTADO DE MATERIAS");

        buttonGroup1.add(buttInscripta);
        buttInscripta.setText("Inscriptas");
        buttInscripta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttInscriptaActionPerformed(evt);
            }
        });

        buttonGroup1.add(buttNOInscripta);
        buttNOInscripta.setText("No Inscriptas");
        buttNOInscripta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttNOInscriptaActionPerformed(evt);
            }
        });

        inscripcionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        inscripcionTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inscripcionTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(inscripcionTable);

        butInscribir.setText("Inscribir");
        butInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butInscribirActionPerformed(evt);
            }
        });

        butAnularInscripcion.setText("Anular Inscripcion");
        butAnularInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAnularInscripcionActionPerformed(evt);
            }
        });

        butSalir.setText("Salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alumnoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(buttInscripta)
                            .addGap(31, 31, 31)
                            .addComponent(buttNOInscripta))
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(butInscribir, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(butAnularInscripcion)
                                .addGap(34, 34, 34)
                                .addComponent(butSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(86, 86, 86))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(alumnoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jLabel3)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttInscripta)
                    .addComponent(buttNOInscripta))
                .addGap(55, 55, 55)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butInscribir)
                    .addComponent(butAnularInscripcion)
                    .addComponent(butSalir))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttNOInscriptaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttNOInscriptaActionPerformed
        
        String alumnoSeleccionado = alumnoComboBox.getSelectedItem().toString();
        String[] partes = alumnoSeleccionado.split(" - ");
        String txtIdAlumno = partes[1];
        int idAlumno = Integer.parseInt(txtIdAlumno);
        ArrayList<Materia> materiasNoInscriptas = inscripcionData.listarMateriasNoCursadas(idAlumno);
        
        DefaultTableModel modelo = (DefaultTableModel) inscripcionTable.getModel();
        modelo.setRowCount(0);
        
        for (Materia materia : materiasNoInscriptas) {
            Object[] fila = {materia.getIdMateria(), materia.getNombre()};
            modelo.addRow(fila);
            
        }
    }//GEN-LAST:event_buttNOInscriptaActionPerformed

    private void buttInscriptaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttInscriptaActionPerformed
        
        String alumnoSeleccionado = alumnoComboBox.getSelectedItem().toString();
        String[] partes = alumnoSeleccionado.split(" - ");
        String txtIdAlumno = partes[1];
        int idAlumno = Integer.parseInt(txtIdAlumno);
        ArrayList<Materia> materiasInscriptas = inscripcionData.listarMateriasCursadas(idAlumno);
        
        DefaultTableModel modelo = (DefaultTableModel) inscripcionTable.getModel();
        modelo.setRowCount(0);
        
        for (Materia materia : materiasInscriptas) {
            Object[] fila = {materia.getIdMateria(), materia.getNombre()};
            modelo.addRow(fila);
        }
    }//GEN-LAST:event_buttInscriptaActionPerformed

    private void alumnoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alumnoComboBoxActionPerformed

    }//GEN-LAST:event_alumnoComboBoxActionPerformed

    private void inscripcionTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inscripcionTableMouseClicked
    }//GEN-LAST:event_inscripcionTableMouseClicked

    private void alumnoComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alumnoComboBoxMouseClicked
        buttonGroup1.clearSelection();
        DefaultTableModel modelo = (DefaultTableModel) inscripcionTable.getModel();
        modelo.setRowCount(0);
    }//GEN-LAST:event_alumnoComboBoxMouseClicked

    private void butInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butInscribirActionPerformed
        int filaSeleccionada = inscripcionTable.getSelectedRow();
        int idMateria = (Integer) inscripcionTable.getValueAt(filaSeleccionada, 0);
        String nombreMateria = (String) inscripcionTable.getValueAt(filaSeleccionada, 1);
        
        String alumnoSeleccionado = alumnoComboBox.getSelectedItem().toString();
        String[] partes = alumnoSeleccionado.split(" - ");
        String txtIdAlumno = partes[1];
        int idAlumno = Integer.parseInt(txtIdAlumno);
        
        Inscripcion ins = new Inscripcion();
        
        ins.setIdAlumno(idAlumno);
        ins.setIdMateria(idMateria);
        ins.setIdInscripto(-1);
        
        inscripcionData.guardarInscripcion(ins);
        JOptionPane.showMessageDialog(null, "La inscripcion se agrego exitosamente!", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_butInscribirActionPerformed

    private void butAnularInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAnularInscripcionActionPerformed
        int filaSeleccionada = inscripcionTable.getSelectedRow();
        int idMateria = (Integer) inscripcionTable.getValueAt(filaSeleccionada, 0);
        String nombreMateria = (String) inscripcionTable.getValueAt(filaSeleccionada, 1);
        
        String alumnoSeleccionado = alumnoComboBox.getSelectedItem().toString();
        String[] partes = alumnoSeleccionado.split(" - ");
        String txtIdAlumno = partes[1];
        int idAlumno = Integer.parseInt(txtIdAlumno);
        
        inscripcionData.borrarInscripcion(idAlumno, idMateria);
    }//GEN-LAST:event_butAnularInscripcionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> alumnoComboBox;
    private javax.swing.JButton butAnularInscripcion;
    private javax.swing.JButton butInscribir;
    private javax.swing.JButton butSalir;
    private javax.swing.JRadioButton buttInscripta;
    private javax.swing.JRadioButton buttNOInscripta;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTable inscripcionTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
