/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Fede-
 */
public class VistaCargaDeNotas extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaCargaDeNotas
     */
    public VistaCargaDeNotas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLab1Titlo = new javax.swing.JLabel();
        jLab2BscrAlmns = new javax.swing.JLabel();
        jTextF1Dni = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTab1Alumnos = new javax.swing.JTable();
        jButt1Buscar = new javax.swing.JButton();
        jButt2GrdarCmbios = new javax.swing.JButton();
        jButtCnlar = new javax.swing.JButton();

        jLab1Titlo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLab1Titlo.setText("Carga De Notas De Alumnos");

        jLab2BscrAlmns.setText("Buscar  Alumno:");

        jTab1Alumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id Alumno", "dni", "Apellido", "nombre", "fechaNacimiento", "estado"
            }
        ));
        jScrollPane1.setViewportView(jTab1Alumnos);
        if (jTab1Alumnos.getColumnModel().getColumnCount() > 0) {
            jTab1Alumnos.getColumnModel().getColumn(0).setResizable(false);
            jTab1Alumnos.getColumnModel().getColumn(1).setResizable(false);
            jTab1Alumnos.getColumnModel().getColumn(2).setResizable(false);
            jTab1Alumnos.getColumnModel().getColumn(3).setResizable(false);
            jTab1Alumnos.getColumnModel().getColumn(4).setResizable(false);
            jTab1Alumnos.getColumnModel().getColumn(5).setResizable(false);
        }

        jButt1Buscar.setText("Buscar");

        jButt2GrdarCmbios.setText("Guardar Cambios");
        jButt2GrdarCmbios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButt2GrdarCmbiosActionPerformed(evt);
            }
        });

        jButtCnlar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLab2BscrAlmns)
                .addGap(139, 139, 139)
                .addComponent(jTextF1Dni, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButt1Buscar)
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jButt2GrdarCmbios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtCnlar)
                .addGap(112, 112, 112))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(174, 250, Short.MAX_VALUE)
                .addComponent(jLab1Titlo)
                .addGap(248, 248, 248))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLab1Titlo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLab2BscrAlmns)
                    .addComponent(jTextF1Dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButt1Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButt2GrdarCmbios)
                    .addComponent(jButtCnlar))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButt2GrdarCmbiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButt2GrdarCmbiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButt2GrdarCmbiosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButt1Buscar;
    private javax.swing.JButton jButt2GrdarCmbios;
    private javax.swing.JButton jButtCnlar;
    private javax.swing.JLabel jLab1Titlo;
    private javax.swing.JLabel jLab2BscrAlmns;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTab1Alumnos;
    private javax.swing.JTextField jTextF1Dni;
    // End of variables declaration//GEN-END:variables
}
