/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Modelo.Alumno;
import Modelo.Materia;
import Persistencia.alumnoData;
import Persistencia.inscripcionData;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Emiliano
 */
public class VistaListarInscripciones extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaListarInscripciones
     */
   private alumnoData alumnoData;
   private inscripcionData inscripcionData;
    
    public VistaListarInscripciones(alumnoData alumnoData,inscripcionData inscripcionData) {
        initComponents();
        this.alumnoData=alumnoData;
        this.inscripcionData=inscripcionData;
        cargarAlumnos();
        
    }
    
      private void cargarAlumnos() {
        BoxAlumno.removeAllItems();
        
        ArrayList<String> apellidoAlumnos = new ArrayList<>();
        ArrayList<Alumno> alumnos = alumnoData.listarAlumnos();
        
        for (Alumno a : alumnos) {
            apellidoAlumnos.add(a.getApellido() + " - " + a.getIdAlumno());
        }
        
        for (String apellido : apellidoAlumnos) {
            BoxAlumno.addItem(apellido);
        }
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButVerInscripciones = new javax.swing.JButton();
        BoxAlumno = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaInscripciones = new javax.swing.JTable();
        ButCerrar = new javax.swing.JButton();
        ButLimpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        ButVerInscripciones.setText("Ver Inscripciones");
        ButVerInscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButVerInscripcionesActionPerformed(evt);
            }
        });

        BoxAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxAlumnoActionPerformed(evt);
            }
        });

        tablaInscripciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "IdMateria", "Materia", "Año", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaInscripciones);

        ButCerrar.setText("Cerrar");
        ButCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButCerrarActionPerformed(evt);
            }
        });

        ButLimpiar.setText("Limpiar");
        ButLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButLimpiarActionPerformed(evt);
            }
        });

        jLabel1.setText("Alumno:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Lista de Inscripciones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BoxAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButVerInscripciones)
                .addGap(55, 55, 55))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(ButLimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButCerrar)
                .addGap(88, 88, 88))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(117, 117, 117))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BoxAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButVerInscripciones)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButCerrar)
                    .addComponent(ButLimpiar))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButLimpiarActionPerformed
        // TODO add your handling code here:
      BoxAlumno.setSelectedIndex(-1);
         DefaultTableModel modelo = (DefaultTableModel) tablaInscripciones.getModel();
          modelo.setRowCount(0);
        
    }//GEN-LAST:event_ButLimpiarActionPerformed

    private void BoxAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxAlumnoActionPerformed
        
    }//GEN-LAST:event_BoxAlumnoActionPerformed

    private void ButCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButCerrarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_ButCerrarActionPerformed

    private void ButVerInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButVerInscripcionesActionPerformed
     String alumnoSeleccionado = BoxAlumno.getSelectedItem().toString();
        String[] partes = alumnoSeleccionado.split(" - ");
        String txtIdAlumno = partes[1];
        int idAlumno = Integer.parseInt(txtIdAlumno);
        ArrayList<Materia> materiasInscriptas = inscripcionData.listarInscripciones(idAlumno);
        
        DefaultTableModel modelo = (DefaultTableModel) tablaInscripciones.getModel();
        modelo.setRowCount(0);
        
        for (Materia materia : materiasInscriptas) {
            Object[] fila = {materia.getIdMateria(), materia.getNombre(),materia.getAño(),materia.isEstado()};
            modelo.addRow(fila);
        }
    }//GEN-LAST:event_ButVerInscripcionesActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BoxAlumno;
    private javax.swing.JButton ButCerrar;
    private javax.swing.JButton ButLimpiar;
    private javax.swing.JButton ButVerInscripciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaInscripciones;
    // End of variables declaration//GEN-END:variables
}
